import type { NextPage } from 'next';
import Head from 'next/head';
import { useAddTank } from 'architecture/applications/addTank';
import { needUpdate } from 'architecture/domains/User';
import { useUserStorage } from 'architecture/util/ defaultService';
import { Loading } from 'components/user/Loading';
import SignInOrOutBtn from 'components/user/signin/SignInOrOutBtn';
import { useRouter } from 'next/router';
import { useCallback, useEffect, useState } from 'react';
import { useAuthState } from 'utils/hooks/useAuthState';
import styles from '../styles/Home.module.css';
import { TankList } from 'components/user/Tank/TankList';

import Modal from '@mui/material/Modal';
import { Fade } from '@mui/material';
import { UserSettingForm } from 'components/user/register/UserSettingForm';

const Home: NextPage = () => {
    const { user } = useUserStorage();
    const addTank = useAddTank();
    const [settingOpen, setSettingOpen] = useState(false);
    const { isLogin, isLoading, userid } = { isLogin: true, isLoading: false, userid: 'amanojs' };
    /* const { isLogin, isLoading, userid } = useAuthState(); */
    const router = useRouter();
    const settingModalCtrl = useCallback(() => {
        if (isLogin && userid && user === undefined) {
            // 総予算と毎月のリセット日を設定するステップポップアップを表示
            setSettingOpen(true);
        }
        if (isLogin && userid && user) {
            setSettingOpen(false);
            addTank({ title: '特別費', badget: 50000 });
        }
    }, [isLogin, user, userid]);

    useEffect(() => {
        settingModalCtrl();
    }, [settingModalCtrl]);

    if (isLoading) return <Loading />;
    if (!isLoading && !isLogin) {
        router.replace('/user/signin');
        return <></>;
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Tankey</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Modal open={settingOpen} closeAfterTransition>
                <Fade in={settingOpen}>
                    <div className="bg-white box-border p-10 h-screen w-screen fixed top-0 overflow-y-scroll">
                        <div className="mx-auto max-w-md">
                            <h3 className="mb-0">基本設定をしましょう</h3>

                            {/* eslint-disable-next-line @next/next/no-img-element */}
                            <img
                                src="https://assets.dryicons.com/uploads/icon/svg/6431/50b3bfff-2a8e-4446-9da2-e37640c06013.svg"
                                alt="namecard"
                                className="w-11/12 mx-auto block"
                            />
                            {userid && <UserSettingForm userid={userid} />}
                        </div>
                    </div>
                </Fade>
            </Modal>

            <SignInOrOutBtn />

            <main className={styles.main}>{user && <TankList />}</main>
        </div>
    );
};

export default Home;
